### ISSUE TITLE
What's with the latest commit?

### ISSUE THREAD

**Issue by solonovamax** [DJtheRedstoner/PerspectiveModv4#17]
![image](https://user-images.githubusercontent.com/46940694/130312068-70096588-9d98-4a00-93c0-d8393b01849a.png)

**Comment by boomboompower** [comment]
See the response in #16

**Comment by LowSpecCorgi** [comment]
It seems people have miss-used this mod

You can always download a old commit for archival purposes and whatnot

**Comment by DJtheRedstoner** [comment]
If you really want to know what happened, here you go:

Some time on Thursday, August 19th, hypixel decides to start enforcing the fact that perspective/freelook mods are against the rules.

In the following hours, this mod, perspectivemod by canelex and perspective mod redux are all blacklisted, and the features in lunar and badlion client are disabled.

Lots of users are upset because perspective mod is one of their favorite mod/cheat. I learn that its used for things like looking around while bridging in bedwars (provides a giant advantage), locking pitch/yaw while bridging or farming and other things that make hypixel's decision to blacklist it reasonable.

Soon afterwards, [caterpillow](https://www.youtube.com/channel/UCgJFj-dRnKCRTOQLIY-tdgA) released [a video](https://www.youtube.com/watch?v=-JoeF7jBMEA&t=2s) showing how to change the modid of MY MOD to bypass the blacklist and including A DOWNLOAD to an already modified version. While this doesn't violate the mod's license in any way, its an asshole move.

Later, the modid that caterpilow changed it to in the download (`notdjperspectivemod`) is blacklisted, which prompts a known cheat developer in this community, [blowsy](https://www.youtube.com/channel/UCaZSjarAwZqW4yTEC5Cq9aw) to [release](https://www.youtube.com/watch?v=Ca5GCDY_1nw) a modified version of my code, that has been merged with timechanger and uses the modid `timechanger` effectively making it unblacklistable.

At some point after this caterpilow updates his download to have a version with the modid `keystrokesmod` making it also unblacklistable.

Hopefully the disgusting actions taken by members of this community explain why I made the decision to "hide" the source code. I am hopeful I will able to "bring it back" once this has all blown over (it will, as all things do).

**Comment by solonovamax** [comment]
Honestly, perhaps consider writing some code to disable the mod if you connect to hypixel with it?

**Comment by DJtheRedstoner** [comment]
> Honestly, perhaps consider writing some code to disable the mod if you connect to hypixel with it?

And then have tutorials made on how to remove said code? I would rather just wait until this quiets down (it will) then I will return the repository to its previous state.

**Comment by solonovamax** [comment]
Well yeah, it's not a permanent solution, but nor is this.

Both are decently easy to work around. So, you could probably just do both of them? Idk.

**Comment by solonovamax** [comment]
If you want to prevent people from cheating, the most you can do is make it difficult to do so.

But in the spirit of free software, there's nothing you can *really* do.
